export const collections = {
  users: "users",
  adminInvites: "adminInvites",
  encryptedGameAccounts: "encryptedGameAccounts",
  heroes: "heroes",
  heroCalendar: "heroCalendar",
  portalOffers: "portalOffers",
  eventWidgets: "eventWidgets",
  donationOffers: "donationOffers",
  news: "news",
  raffleEntries: "raffleEntries",
  marketplaceAccounts: "marketplaceAccounts",
  topupLeads: "topupLeads",
  referralCodes: "referralCodes",
  referralRewards: "referralRewards",
  bonusTransactions: "bonusTransactions",
  chatRooms: "chatRooms",
  chatMessages: "chatMessages",
  clanAnnouncements: "clanAnnouncements",
  forumThreads: "forumThreads",
  crmTables: "crmTables",
  moderationQueue: "moderationQueue",
  siteSettings: "siteSettings",
  globalUserBlocks: "globalUserBlocks"
} as const;
